"""Parse Claude Code session JSONL transcripts into a flat, renderable event stream.

A transcript is an append-only JSONL file where each line is one of:

  * a conversational entry  (``type`` in ``user`` / ``assistant``)
  * a session sidecar       (``ai-title``, ``last-prompt``, ``mode``, ...)
  * a UI bookkeeping entry  (``queue-operation``, ``permission-mode``, ...)

Only the first group carries a ``message``.  Everything else is metadata that
we fold into a :class:`Session` header instead of the timeline.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from typing import Any, Iterable, Iterator

# --------------------------------------------------------------------------- #
# constants
# --------------------------------------------------------------------------- #

CONVERSATION_TYPES = {"user", "assistant"}

#: tool results larger than this are truncated when *displayed* (never when
#: indexed -- search always sees the full text).
DISPLAY_LIMIT = 4000

#: system-reminder / hook noise that should not pollute search results.
_NOISE_RE = re.compile(
    r"^\s*<(?:system-reminder|command-name|command-message|local-command-stdout)"
    r"|^\s*Caveat: The messages below were generated by the user while running local commands"
)

_IMAGE_MARKER = "[image]"


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #

def _tool_result_text(content: Any) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, dict):
                if block.get("type") == "text":
                    parts.append(block.get("text") or "")
                elif block.get("type") == "image":
                    parts.append(_IMAGE_MARKER)
            elif isinstance(block, str):
                parts.append(block)
        return "\n".join(parts)
    if content is None:
        return ""
    return str(content)


def _is_noise(text: str) -> bool:
    return bool(_NOISE_RE.match(text))


#: ``origin.kind`` values that mean "the harness wrote this, not the human".
_SYSTEM_ORIGINS = {"task-notification", "peer"}


def _is_system_injected(rec: dict) -> bool:
    """True for ``type: "user"`` records the harness generated itself.

    A background task finishing shows up as a user turn whose ``origin.kind``
    is ``task-notification`` and whose ``promptSource`` is ``system``.  Those
    are not instructions, so they must not be counted as prompts or used as a
    session title.
    """
    origin = rec.get("origin")
    if isinstance(origin, dict) and origin.get("kind") in _SYSTEM_ORIGINS:
        return True
    return rec.get("promptSource") == "system"


def _system_title(text: str) -> str:
    """One-line summary for a system-injected record."""
    m = re.search(r"<summary>(.*?)</summary>", text, re.S)
    if m:
        return " ".join(m.group(1).split())[:160]
    m = re.search(r"<([a-z-]+)>", text)
    return f"<{m.group(1)}>" if m else "system"


def _summarize_tool_input(name: str, inp: Any) -> str:
    """One-line human summary of a tool call, used as the timeline title."""
    if not isinstance(inp, dict):
        return ""
    for key in ("command", "file_path", "path", "pattern", "url", "query", "prompt", "skill"):
        val = inp.get(key)
        if isinstance(val, str) and val.strip():
            line = val.strip().splitlines()[0]
            return line[:160]
    if name == "TaskCreate" or name == "TaskUpdate":
        return str(inp.get("subject") or inp.get("taskId") or "")
    keys = ", ".join(list(inp)[:4])
    return f"({keys})" if keys else ""


def _iso(ts: Any) -> str:
    return ts if isinstance(ts, str) else ""


# --------------------------------------------------------------------------- #
# data model
# --------------------------------------------------------------------------- #

@dataclass
class Event:
    """One renderable row of a conversation."""

    uuid: str
    parent_uuid: str | None
    kind: str          # prompt | assistant | thinking | tool_use | tool_result | system
    ts: str
    text: str = ""
    tool: str = ""
    tool_use_id: str = ""
    title: str = ""
    model: str = ""
    truncated: bool = False
    meta: dict = field(default_factory=dict)

    def display_text(self, limit: int = DISPLAY_LIMIT) -> str:
        if len(self.text) <= limit:
            return self.text
        self.truncated = True
        return self.text[:limit]


@dataclass
class Session:
    """A parsed transcript."""

    id: str
    path: str
    project: str = ""
    source: str = "claude"   # claude | codex
    cwd: str = ""
    git_branch: str = ""
    version: str = ""
    title: str = ""
    slug: str = ""
    first_ts: str = ""
    last_ts: str = ""
    events: list[Event] = field(default_factory=list)
    prompts: list[str] = field(default_factory=list)
    models: list[str] = field(default_factory=list)
    tools: dict[str, int] = field(default_factory=dict)
    n_user: int = 0
    n_assistant: int = 0
    n_tool: int = 0
    n_thinking: int = 0
    size: int = 0
    mtime: float = 0.0
    parse_errors: int = 0

    @property
    def n_events(self) -> int:
        return len(self.events)

    @property
    def duration_s(self) -> float:
        a, b = _parse_ts(self.first_ts), _parse_ts(self.last_ts)
        return max(0.0, b - a) if a and b else 0.0


def _parse_ts(ts: str) -> float:
    if not ts:
        return 0.0
    try:
        from datetime import datetime

        return datetime.fromisoformat(ts.replace("Z", "+00:00")).timestamp()
    except Exception:
        return 0.0


# --------------------------------------------------------------------------- #
# parsing
# --------------------------------------------------------------------------- #

def project_of(path: str, root: str) -> str:
    """Derive the project bucket from the on-disk layout.

    ``~/.claude/projects/<encoded-cwd>/<session>.jsonl`` -- the encoded cwd is
    lossy (``/`` and ``-`` both become ``-``), so we prefer the real ``cwd``
    recorded inside the transcript and fall back to the directory name.
    """
    rel = os.path.relpath(path, root)
    return rel.split(os.sep)[0] if os.sep in rel else ""


def iter_lines(path: str) -> Iterator[dict]:
    """Yield parsed JSON objects, skipping blank/corrupt lines."""
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except (json.JSONDecodeError, ValueError):
                continue
            if isinstance(obj, dict):
                yield obj


def parse_session(path: str, root: str = "") -> Session:
    """Parse one transcript file into a :class:`Session`."""
    st = os.stat(path)
    sid = os.path.splitext(os.path.basename(path))[0]
    sess = Session(id=sid, path=path, size=st.st_size, mtime=st.st_mtime,
                   project=project_of(path, root) if root else "")

    models: dict[str, None] = {}
    tools: dict[str, int] = {}
    prompts: list[str] = []
    seen_uuids: set[str] = set()
    tool_use_names: dict[str, str] = {}

    for obj in iter_lines(path):
        etype = obj.get("type")

        # ---- sidecar metadata -------------------------------------------- #
        if etype == "ai-title":
            sess.title = obj.get("aiTitle") or sess.title
            continue
        if etype == "last-prompt":
            if not prompts:
                lp = obj.get("lastPrompt")
                if isinstance(lp, str) and lp.strip():
                    prompts.append(lp.strip())
            continue
        if etype not in CONVERSATION_TYPES:
            continue

        # ---- header fields ------------------------------------------------ #
        sess.cwd = sess.cwd or obj.get("cwd") or ""
        sess.git_branch = sess.git_branch or obj.get("gitBranch") or ""
        sess.version = sess.version or obj.get("version") or ""
        sess.slug = sess.slug or obj.get("slug") or ""
        ts = _iso(obj.get("timestamp"))
        if ts:
            sess.first_ts = sess.first_ts or ts
            sess.last_ts = ts

        msg = obj.get("message")
        if not isinstance(msg, dict):
            continue
        role = msg.get("role") or etype
        content = msg.get("content")
        uuid = obj.get("uuid") or ""
        parent = obj.get("parentUuid")
        if uuid:
            if uuid in seen_uuids:
                continue
            seen_uuids.add(uuid)

        # ---- assistant ---------------------------------------------------- #
        if role == "assistant":
            sess.n_assistant += 1
            model = msg.get("model")
            if model and model != "<synthetic>":
                models.setdefault(model, None)
            if not isinstance(content, list):
                continue
            for block in content:
                if not isinstance(block, dict):
                    continue
                btype = block.get("type")
                if btype == "thinking":
                    text = block.get("thinking") or ""
                    if not text.strip():
                        continue
                    sess.n_thinking += 1
                    sess.events.append(Event(
                        uuid=uuid, parent_uuid=parent, kind="thinking", ts=ts,
                        text=text, model=model or ""))
                elif btype == "text":
                    text = block.get("text") or ""
                    if not text.strip():
                        continue
                    sess.events.append(Event(
                        uuid=uuid, parent_uuid=parent, kind="assistant", ts=ts,
                        text=text, model=model or ""))
                elif btype == "tool_use":
                    name = block.get("name") or "?"
                    inp = block.get("input")
                    tid = block.get("id") or ""
                    tool_use_names[tid] = name
                    tools[name] = tools.get(name, 0) + 1
                    sess.n_tool += 1
                    sess.events.append(Event(
                        uuid=uuid, parent_uuid=parent, kind="tool_use", ts=ts,
                        tool=name, tool_use_id=tid, model=model or "",
                        title=_summarize_tool_input(name, inp),
                        text=json.dumps(inp, ensure_ascii=False, indent=2)
                        if inp is not None else ""))
            continue

        # ---- user --------------------------------------------------------- #
        # Not every ``type: "user"`` record is something the human typed.
        # Background-task completions, hook output and SDK traffic arrive the
        # same way; ``origin``/``promptSource`` is what tells them apart.
        if _is_system_injected(obj):
            if isinstance(content, str) and content.strip():
                sess.events.append(Event(
                    uuid=uuid, parent_uuid=parent, kind="system", ts=ts,
                    text=content, title=_system_title(content),
                    meta={"origin": (obj.get("origin") or {}).get("kind")}))
            continue

        if isinstance(content, str):
            text = content
            if _is_noise(text):
                continue
            sess.n_user += 1
            prompts.append(text.strip())
            sess.events.append(Event(
                uuid=uuid, parent_uuid=parent, kind="prompt", ts=ts, text=text))
            continue

        if not isinstance(content, list):
            continue
        for block in content:
            if not isinstance(block, dict):
                continue
            btype = block.get("type")
            if btype == "tool_result":
                tid = block.get("tool_use_id") or ""
                text = _tool_result_text(block.get("content"))
                sess.events.append(Event(
                    uuid=uuid, parent_uuid=parent, kind="tool_result", ts=ts,
                    text=text, tool=tool_use_names.get(tid, ""),
                    tool_use_id=tid,
                    meta={"is_error": bool(block.get("is_error"))}))
            elif btype == "text":
                text = block.get("text") or ""
                if not text.strip() or _is_noise(text):
                    continue
                sess.n_user += 1
                prompts.append(text.strip())
                sess.events.append(Event(
                    uuid=uuid, parent_uuid=parent, kind="prompt", ts=ts, text=text))
            elif btype == "image":
                sess.events.append(Event(
                    uuid=uuid, parent_uuid=parent, kind="image", ts=ts,
                    text=_IMAGE_MARKER, meta=_image_meta(block)))

    sess.models = list(models)
    sess.tools = tools
    sess.prompts = prompts
    if not sess.title and prompts:
        sess.title = prompts[0].strip().splitlines()[0][:120]
    return sess


def _image_meta(block: dict) -> dict:
    src = block.get("source")
    if isinstance(src, dict):
        return {"media_type": src.get("media_type") or "image/png",
                "data": src.get("data") or ""}
    return {}


# --------------------------------------------------------------------------- #
# discovery
# --------------------------------------------------------------------------- #

def default_root() -> str:
    return os.environ.get("CLAUDELOG_ROOT") or os.path.join(
        os.path.expanduser("~"), ".claude", "projects")


def codex_root() -> str:
    """Where the Codex CLI keeps its rollouts."""
    return os.environ.get("CLAUDELOG_CODEX_ROOT") or os.path.join(
        os.path.expanduser("~"), ".codex", "sessions")


def discover_codex(root: str) -> list[tuple[str, int, float]]:
    """Return ``(path, size, mtime)`` for every Codex rollout under *root*."""
    found: list[tuple[str, int, float]] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in ("node_modules", ".git")]
        for fn in filenames:
            if not (fn.startswith("rollout-") and fn.endswith(".jsonl")):
                continue
            path = os.path.join(dirpath, fn)
            try:
                st = os.stat(path)
            except OSError:
                continue
            found.append((path, st.st_size, st.st_mtime))
    found.sort(key=lambda t: t[2], reverse=True)
    return found


def discover(root: str) -> list[tuple[str, int, float]]:
    """Return ``(path, size, mtime)`` for every transcript under *root*."""
    found: list[tuple[str, int, float]] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in ("node_modules", ".git")]
        for fn in filenames:
            if not fn.endswith(".jsonl"):
                continue
            path = os.path.join(dirpath, fn)
            try:
                st = os.stat(path)
            except OSError:
                continue
            found.append((path, st.st_size, st.st_mtime))
    found.sort(key=lambda t: t[2], reverse=True)
    return found


def searchable_text(sess: Session) -> str:
    """Concatenate everything worth indexing for one session."""
    chunks: list[str] = []
    for ev in sess.events:
        if ev.kind == "image":
            continue
        if ev.kind == "tool_use":
            chunks.append(f"{ev.tool} {ev.title}\n{ev.text}")
        elif ev.kind == "tool_result":
            chunks.append(ev.text)
        else:
            chunks.append(ev.text)
    return "\n\n".join(chunks)


def iter_prompts(sess: Session) -> Iterable[str]:
    return sess.prompts
